add_newline = false

[custom.prod_k8s_env]
command = 'echo K8S-PROD' # shows output of command
detect_files = ['foo'] # can specify filters but wildcards are not supported
when = ''' test "$K8SENV" = "production" '''
format = ' [$output]($style)'
style = 'bold red'

[custom.dev_stg_k8s_env]
command = 'echo K8S-DEV' # shows output of command
detect_files = ['foo'] # can specify filters but wildcards are not supported
when = ''' test "$K8SENV" = "dev-stg" '''
format = ' [$output]($style)'
style = 'bold green'

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# [battery]
# full_symbol = "- "
# charging_symbol = "+ "
# discharging_symbol = "* "

# [[battery.display]]  # "bold red" style when capacity is between 0% and 10%
# threshold = 10
# style = "bold red"

# [[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
# threshold = 30
# style = "bold yellow"

# [[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
# threshold = 100
# style = "bold green"
# discharging_symbol = "-"
# charging_symbol = "-"

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = -1
symbol = "mem "
separator = " | swp "
style = "bold dimmed cyan"