;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		c-electric-colon
		c-electric-delete-forward
		c-electric-lt-gt
		c-electric-semi&comma
		c-electric-star
		c-indent-line-or-region
		complete-symbol
		dabbrev-expand
		downcase-region
		indent-for-tab-command
		julia-latexsub-or-indent
		keyboard-escape-quit
		kill-region
		sh-assignment
		suspend-frame
		yaml-electric-backspace
		yaml-electric-dash-and-dot
		))

(setq mc/cmds-to-run-once
      '(
		beginning-of-buffer
		xterm-paste
		))
